language: rust
sudo: false
cache: false
os:
  - linux
  - windows
  - osx
rust:
  - stable
  - beta
  - nightly

script:
  - cargo build --verbose --no-default-features
  - cargo build --verbose
  - cargo test --verbose
  - if [ ${TRAVIS_RUST_VERSION} == "stable" ]; then cargo test --features=doc-comment; fi

before_script:
  - if [ ${TRAVIS_RUST_VERSION} == "stable" ]; then
      rustup component add clippy-preview rustfmt;
      cargo fmt --all -- --check;
      cargo clippy --all-targets --all-features -- -Dwarnings
    fi
notifications:
  email:
    on_success: never
