language: rust
sudo: false
cache: false
os:
  - linux
  - windows
  - osx
rust:
  - stable
  - beta
  - nightly

script:
  - cargo build --verbose
  - echo "" | cargo test --verbose

before_script:
  - if [ ${TRAVIS_RUST_VERSION} == "stable" ]; then
      rustup component add clippy-preview rustfmt;
      cargo fmt --all -- --check;
      cargo clippy --all-targets --all-features -- -Dwarnings;
    fi
notifications:
  email:
    on_success: never